name: Publish

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: nightly

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        distro:
          - centos:7
          - rockylinux:8
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/docker/login-action
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get target tag
        id: tag
        run: echo "TAG=${{ matrix.distro }}" | sed 's|:|-|' >> "${GITHUB_OUTPUT}"

      # https://github.com/docker/build-push-action
      - uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile.${{ steps.tag.outputs.TAG }}
          tags: ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.TAG }}
